### ISSUE TITLE
non-existent tarball breaks compilation of the lvm2 utils package

### ISSUE THREAD

**Issue by takinbo** [CZ-NIC/turris-os-packages#15]
While trying to build the turris-os firmware, my build kept failing due to a non-existent tarball in the redhat lvm2 repository - ftp://sources.redhat.com/pub/lvm2. The missing file is `LVM2.2.02.145.tgz`. Maybe we could use the [fedora repository](http://pkgs.fedoraproject.org/repo/pkgs/lvm2/) instead?

**Comment by takinbo** [comment]
It seems the better url to use is - ftp://sources.redhat.com/pub/lvm2/releases

**Comment by sairon** [comment]
Thanks, solved in bad99749cd3d970e3f74341b37b3171a25071a2b.
