### ISSUE TITLE
syslog-ng upgrade

### ISSUE THREAD

**Issue by czanik** [CZ-NIC/turris-os-packages#19]
Currently Turris Omnia has syslog-ng version 3.0

syslog-ng 3.8.1 was released recently, which -- among many other features -- introduced disk-based buffering. It would be very useful when logging to a remote server.

I don't have any OpenWRT packaging experience, but work at syslog-ng upstream and ready to help if you have any questions.

A few notes about upgrading:
- syslog-ng.conf now requires a version number declaration on the first line: https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-3.8-guides/en/syslog-ng-ose-v3.8-guide-admin/html-single/index.html#configuration-syntax
- a few more minor config changes might be suggested by syslog-ng on startup
- JSON is not a mandatory dependency, but could be useful when logging to some cloud providers: https://www.loggly.com/blog/sending-json-format-logs-syslog-ng/
- There are tons of new destinations and thus build dependencies, but not really necessary for current functionality

**Comment by Privacywonk** [comment]
I am trying to run down a logging issue with the current syslog-ng implementation:

I have snort up and running with a directive in snort.conf to use syslog:
`output alert_syslog: LOG_AUTH LOG_ALERT`

syslog-ng.conf:
```
cat /etc/syslog-ng.conf
@version:3.0

options {
 chain_hostnames(no);
 flush_lines(0);
 stats_freq(0);
 flush_lines(0);
 log_msg_size(65536);
};

source src {
 internal();
 unix-dgram("/dev/log");
};

source kernel {
        file("/proc/kmsg" program_override("kernel"));
};

filter f_turris_iptables {
 not match(".*turris[^:]*: .*" value(MESSAGE)) or not level(debug);
};

destination messages {
 file("/var/log/messages" suppress(5) template("${ISODATE} ${PRIORITY} ${PROGRAM}[${PID}]: ${MSGONLY}\n") log_fifo_size(256));
};

log {
 source(src);
 source(kernel);
 filter(f_turris_iptables);
 destination(messages);
};

include "/etc/syslog-ng.d/";
```

When I `cat /var/log/messages` - the output does not show snort messages or alerts. However, if I `cat /var/log/messages |grep snort` - suddenly I have alerts. 

In addition, I have all my logs being forwarded to an instance of graylog. The snort alerts do not appear there either.

This is strange behavior, to me. Any guidance / insight?

**Comment by ja-pa** [comment]
Turris Omnia syslog-ng version is now 3.10.1 so I'm closing this issue. 
Anyway thanks for reporting, we will try to keep pace with upstream.
