### ISSUE TITLE
Package Request: mlocate

### ISSUE THREAD

**Issue by dshcherb** [CZ-NIC/turris-os-packages#22]
root@turris:~# opkg install mlocate
Unknown package 'mlocate'.
Collected errors:
 * opkg_install_cmd: Cannot install package mlocate.

Present in the Entware - quite useful for quick file lookups.
https://github.com/Entware-ng/Entware-ng/blob/48214f6101b2cc9a9421740cbf00521feb06a688/configs/x64.config#L5678

opkg list | grep mlocate
mlocate - 0.26-1 - Quickly find files on the filesystem based on their name mlocate is a new implementation of locate, a tool to find files anywhere in the filesystem based on their name, using a fixed pattern or a regular expression. Unlike other tools like find(1), locate uses a previously created database to perform the search, allowing queries to execute much faster. This database is updated periodically from cron.

I would appreciate if you could add it to the Turris repos.

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/turris-os-packages/issues/71
