### ISSUE TITLE
Package request: gpgv

### ISSUE THREAD

**Issue by Grief** [CZ-NIC/turris-os-packages#29]
Cannot find `gpgv `among the packages. However I can see that openwrt feeds provie it.

It is needed because of that:

```
lxc-create -t ubuntu
Checking cache download in /var/cache/lxc/yakkety/rootfs-armhf ...
Installing packages in template: ssh,vim,language-pack-en
Downloading ubuntu minimal ...
I: Retrieving Release
I: Retrieving Release.gpg
I: Checking Release signature
E: Error executing gpgv to check Release signature
lxc-create: lxccontainer.c: create_run_template: 1201 container creation template for ubuntu failed
lxc-create: lxc_create.c: main: 274 Error creating container ubuntu

```

**Comment by Grief** [comment]
I've spent some time to learn about openwrt build chain and can confirm that this package can be built without an issue. I guess it is missing because it was added recently, in September of 2016: https://github.com/openwrt/packages/commit/933e84cc7f9ebf5e3be2dac51c8946aa97dbc229

I used your docker image `turris/turris-os-build:omnia-toolchain` for build, `wget`-ed the updated version of the `Makefile`, checked `gpgv` in `make menuconfig` and run `make package/feeds/packages/gnupg/compile`. Package appeared in `bin/mvebu-musl/packages/packages/`, I've installed it but now another error apears while creating ubuntu lxc container:
`/usr/share/lxc/templates/lxc-ubuntu: line 386: lxc-unshare: command not found`

**Comment by ja-pa** [comment]
Thanks for reporting, 
gpgv package is now in our test branch and will be part of next release
https://gitlab.labs.nic.cz/turris/turris-os-packages/commit/722f7448d81b1484cf196fafed5a5e26e9966691 
http://repo.turris.cz/omnia-nightly/packages/turrispackages/gpgv_1.4.21-1_mvebu.ipk

btw you can also use command 
**lxc-create -t download --name myname**
to create lxc  (see https://www.turris.cz/doc/en/howto/lxc )
