### ISSUE TITLE
Package request: irqbalance

### ISSUE THREAD

**Issue by rsalvaterra** [CZ-NIC/turris-os-packages#30]
Omnia's Armada 385 is dual core, irqbalance should be installed for better performance (it should even be part of the base installation).

**Comment by ja-pa** [comment]
Thanks for suggestion, irqbalance is now in our test repo https://gitlab.labs.nic.cz/turris/turris-os-packages/commit/a6976096032b1567452b16225c8984a2d104e981 and it'll be part of 3.9 release

Right now it's not in base instalation, I'll try make some benchmark and we'll see if there is performance improvement
