### ISSUE TITLE
Unbound hardening - Qname-Minimisation

### ISSUE THREAD

**Issue by Koleon** [CZ-NIC/turris-os-packages#32]
Please make following settings default in unbound config file:
qname-minimisation: yes
harden-below-nxdomain: yes

**Comment by ja-pa** [comment]
Thanks for reporting. I'm testing unbound with these settings in my repo, and it will be probably in release 3.8. https://github.com/CZ-NIC/turris-os-packages/commit/91b62e16557cd57793578017171e9d4331a59bf3

**Comment by ja-pa** [comment]
It's now in test branch and will be part of 3.8 release https://gitlab.labs.nic.cz/turris/turris-os-packages/commit/655208dc3991b43cc05642596571da4a011fc83b
