### ISSUE TITLE
Package request: tmux

### ISSUE THREAD

**Issue by cmacq2** [CZ-NIC/turris-os-packages#36]
Could `tmux` be included as part of the utilities? It makes working with SSH a lot safer, and allows you to resume previous SSH sessions where you left off.

OpenWRT includes a `tmux` opkg: https://github.com/openwrt/packages/tree/master/utils/tmux

**Comment by ja-pa** [comment]
Hi,
tmux is already part of our repository see http://repo.turris.cz/omnia-stable/packages/packages/tmux_2.2-1_mvebu.ipk 
You could install it with opkg update && opkg install tmux
I'm closing this issue.
