### ISSUE TITLE
Update request: dnsmasq

### ISSUE THREAD

**Issue by voltagex** [CZ-NIC/turris-os-packages#41]
https://forum.turris.cz/t/dnsmasq-cves-please-provide-updates/5166

Please update dnsmasq to the newest version.

**Comment by ja-pa** [comment]
Thx for reporting we have new version in our test branch https://gitlab.labs.nic.cz/turris/openwrt/commit/90df9db428e93123d32da49fe1585408bdf1869a , so it should be part of next release.

**Comment by ja-pa** [comment]
Updated dnsmasq was released in Turris OS 3.8.3.
