### ISSUE TITLE
Feature request: Update bash build configuration to include --enable-job-control

### ISSUE THREAD

**Issue by doctorjames** [CZ-NIC/turris-os-packages#42]
Further to [my forum post](https://forum.turris.cz/t/support-job-control-in-bash-so-sigstop-susp-is-usable-in-an-ssh-terminal/5174), can bash be built with `--enable-job-control`? Are there any issues relating to this being enabled, or is it inherited from OpenWRT and omitted purely for binary size purposes on non-Turris routers?

It's likely someone that has installed `bash` and is using it as their shell is likely to expect it to be fully functional. (Incidentally, Turris's `busybox/ash` does enable job control.)

**Comment by ja-pa** [comment]
I don't know any specific reason why job control should be disabled. I'm testing it in my branch, after that it could be part of future release (probably after 3.8.3 )

https://gitlab.labs.nic.cz/turris/turris-os-packages/commit/f61b6208c2dd61952c3c7b16ca4d1ed7fbdd88eb

**Comment by sairon** [comment]
I enabled job control previously in the past using these two commits:
c391167e7842ca6cb8a6fc1a98953b05ec17fe19
351f40d83fa44ad4c0c0979339f155d2f39fd057

However this commit (probably unintentionally) removed the changes: 848dfeb836102a381cfb1657ce85b420b2842f9f

I suggest to do it the cleaner way - just as it has been done previously (and also re-introduce the named pipes support). This is also waiting for upstream merge, however the bash package maintainer is not responsive: https://github.com/openwrt/packages/pull/3252

**Comment by ja-pa** [comment]
Merged in 3.8.5, thanks
