### ISSUE TITLE
Package Request: Node-Red

### ISSUE THREAD

**Issue by renne** [CZ-NIC/turris-os-packages#52]
[Node-Red](https://nodered.org/) is a powerful [node.js](https://nodejs.org/en/about/) graphical flow-based programming and run-time environment for IOT applications [originally devloped by IBM and later released under Apache license](https://en.wikipedia.org/wiki/Node-RED). Without programming skills you can click together e.g. the complete control flows for all IOT devices in your home. Currently it provides over 2,400 nodes to build flow diagrams (I/O-, database-, services-nodes like MQTT, Alexa, Google-IoT, IBM-Watson, ...). It also provides a function node for custom Javascript code.

[Introduction video](https://www.youtube.com/watch?time_continue=1&v=vYreeoCoQPI)

[Example Makefile](https://github.com/nxhack/openwrt-node-packages/tree/master/node-node-red)

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/turris-os-packages/issues/253
