### ISSUE TITLE
Nextcloud: Missing cronjob

### ISSUE THREAD

**Issue by renne** [CZ-NIC/turris-os-packages#53]
`/usr/bin/php-cli -f /srv/www/nextcloud/cron.php` has to be run every 15 minutes with the same user like the web-server.

**Comment by renne** [comment]
Add the following in crontab:
```
# Nextcloud every 15 minutes
*/15  *  *  *  *   /usr/bin/su --shell /bin/ash --command '/usr/bin/php-cli -f /srv/www/nextcloud/cron.php' nobody
```

**Comment by ja-pa** [comment]
Moved to https://gitlab.labs.nic.cz/turris/turris-os-packages/issues/254
