### ISSUE TITLE
No current TOR package

### ISSUE THREAD

**Issue by renne** [CZ-NIC/turris-os-packages#55]
Hi,

as anonymity is a cat-and-mouse game outdated TOR packages are dangerous. TurrisOS installs version 2.9.15 while [0.3.4.8](https://gitweb.torproject.org/tor.git/plain/ReleaseNotes?id=tor-0.3.4.8) is current.

This is a security issue.

**Comment by ja-pa** [comment]
Hi,
Tor version 0.2.9 is still supported by Torproject (see https://gitweb.torproject.org/tor.git/tree/ChangeLog?h=release-0.2.9), so when it comes to security issue situation isn't so bad. 
However, we'll switch to 0.3 as soon as possible mainly because of v3 onion services.

**Comment by ja-pa** [comment]
Updated version of tor package is now in nightly branch and will be part of next major release. Thanks
